SELECT* FROM SALARIES
ORDER BY Salary DESC;

SELECT EMPLOYEES.first_name, EMPLOYEES.last_name, EMPLOYEES.role, SALARIES.salary
FROM EMPLOYEES
JOIN SALARIES ON SALARIES.employee_id = EMPLOYEES.employee_id;

SELECT EMPLOYEES.first_name, EMPLOYEES.last_name, EMPLOYEES.role, PROJECTS.project_name
FROM EMPLOYEES
INNER JOIN EMPLOYEE_PROJECTS ON EMPLOYEES.employee_id = EMPLOYEE_PROJECTS.employee_id
JOIN PROJECTS ON EMPLOYEE_PROJECTS.project_id = PROJECTS.project_id;

SELECT* FROM EMPLOYEES;

SELECT EMPLOYEES.first_name, EMPLOYEES.last_name, EMPLOYEES.role, PROJECTS.project_name
FROM EMPLOYEES
INNER JOIN EMPLOYEE_PROJECTS ON EMPLOYEES.employee_id = EMPLOYEE_PROJECTS.employee_id
JOIN PROJECTS ON EMPLOYEE_PROJECTS.project_id = PROJECTS.project_id;

SELECT first_name, last_name
FROM EMPLOYEES
LEFT JOIN  EMPLOYEE_PROJECTS ON EMPLOYEES.employee_id = EMPLOYEE_PROJECTS.employee_id
WHERE EMPLOYEE_PROJECTS._id IS NULL;

SELECT e.first_name, e.last_name, p.project_name
FROM EMPLOYEES e
LEFT JOIN  EMPLOYEE_PROJECTS ep ON e.employee_id = ep.employee_id
INNER JOIN PROJECTS p ON p.project_id = ep.project_id;

DELETE FROM EMPLOYEE_PROJECTS 
WHERE employee_id = 104;